Fix testShowMissingEntity with clearHooks
EntityHandler::showMissingEntity() triggers a parse, which
can cause a hook handler to run for an unrelated extension
where database access occurs.

This can cause a test failure:
RuntimeException: Database backend disabled

We can run clearHooks for ParserAfterParse to give a more
clean test environment and fix this issue.

Also fixed a deprecation warning for wfArrayPlus2d.

Bug: T427120
Change-Id: I04c1bafafea50feb4e9699d108818da7ca104bb1